TestCropBox:
  disabled: false
  limits: [-0.5, -0.5, 0.1, 0.5, 0.5, 1.0]
  marker_color: [0.0, 1.0, 0.0]
  negative: false
  organized: false
  pub_marker: true
  transform: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
TestPublisher: {disabled: false, output_topic: output}
chain_description: ['TestCropBox, filter/cropbox', 'TestPublisher, output/publisher']
disabled: false
input_topic: /camera/depth_registered/points
